name: Daily Bazi Multi-Platform Post

on:
  workflow_dispatch: # Manual triggering only - no automatic schedule

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: 📦 Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
          
    - name: 📦 Install dependencies
      run: |
        echo "Cache hit: ${{ steps.cache-npm.outputs.cache-hit }}"
        npm install
      
    - name: 🔤 Install Chinese fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra
        sudo fc-cache -fv
        
    - name: 🔍 Validate environment variables
      run: |
        echo "Checking required credentials..."
        
        # Check Twitter credentials if enabled
        if [ "$ENABLE_TWITTER" != "false" ]; then
          if [ -z "$TWITTER_API_KEY" ] || [ -z "$TWITTER_API_SECRET" ] || [ -z "$TWITTER_ACCESS_TOKEN" ] || [ -z "$TWITTER_ACCESS_SECRET" ]; then
            echo "❌ Missing required Twitter API credentials"
            exit 1
          fi
          echo "✅ Twitter credentials validated"
        fi
        
        # Check Telegram credentials if enabled
        if [ "$ENABLE_TELEGRAM" != "false" ]; then
          if [ -z "$TELEGRAM_BOT_TOKEN" ] || [ -z "$TELEGRAM_CHANNEL_ID" ]; then
            echo "❌ Missing required Telegram credentials"
            exit 1
          fi
          echo "✅ Telegram credentials validated"
        fi
        
        echo "✅ All required credentials validated"
      env:
        ENABLE_TWITTER: ${{ vars.ENABLE_TWITTER || 'true' }}
        ENABLE_TELEGRAM: ${{ vars.ENABLE_TELEGRAM || 'true' }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        
    - name: 🚀 Run multi-platform posting
      run: npm start
      env:
        ENABLE_TWITTER: ${{ vars.ENABLE_TWITTER || 'true' }}
        ENABLE_TELEGRAM: ${{ vars.ENABLE_TELEGRAM || 'true' }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }} 