name: Daily Bazi Facebook

on:
  schedule:
    # Run daily at 00:15 UTC (5 minutes after Telegram)
    - cron: '15 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  facebook:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: 📦 Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
          
    - name: 📦 Install dependencies
      run: |
        echo "Cache hit: ${{ steps.cache-npm.outputs.cache-hit }}"
        npm install
      
    - name: 🔤 Install Chinese fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra
        sudo fc-cache -fv
        
    - name: 🔍 Validate environment variables
      run: |
        echo "Checking required Facebook credentials..."
        if [ -z "$FACEBOOK_PAGE_ACCESS_TOKEN" ] || [ -z "$FACEBOOK_PAGE_ID" ]; then
          echo "❌ Missing required Facebook credentials"
          exit 1
        fi
        echo "✅ Environment variables validated"
      env:
        FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
        FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
        
    - name: 🚀 Capture portrait screenshot and post to Facebook
      run: npm run facebook
      env:
        FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
        FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
