name: Daily Bazi Tweet

on:
  schedule:
    # Run daily at 15:00 UTC (11pm SGT)
    - cron: '00 15 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  tweet:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: 📦 Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
          
    - name: 📦 Install dependencies
      run: |
        echo "Cache hit: ${{ steps.cache-npm.outputs.cache-hit }}"
        npm install
      
    - name: 🔤 Install Chinese fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra
        sudo fc-cache -fv
        
    - name: 🔍 Validate environment variables
      run: |
        echo "Checking required Twitter API credentials..."
        if [ -z "$TWITTER_API_KEY" ] || [ -z "$TWITTER_API_SECRET" ] || [ -z "$TWITTER_ACCESS_TOKEN" ] || [ -z "$TWITTER_ACCESS_SECRET" ]; then
          echo "❌ Missing required Twitter API credentials"
          exit 1
        fi
        echo "✅ Environment variables validated"
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        
    - name: 🚀 Capture screenshot and post tweet
      run: npm run tweet
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }} 
